// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20200330225056_refatorReviewTable")]
    partial class refatorReviewTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("Landmark")
                        .IsRequired();

                    b.Property<double>("Rating");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Paris",
                            Country = "France",
                            Landmark = "Louvre Museum",
                            Rating = 0.0
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Sydney",
                            Country = "Australia",
                            Landmark = "Opera House",
                            Rating = 0.0
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Portland",
                            Country = "USA",
                            Landmark = "Pittock Mansion",
                            Rating = 0.0
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Bangkok",
                            Country = "Thailand",
                            Landmark = "Temple of the Emerald Buddha",
                            Rating = 0.0
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Seoul",
                            Country = "Korea",
                            Landmark = "Gyeongbokgung Palace",
                            Rating = 0.0
                        });
                });

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("DestinationId");

                    b.Property<int>("Rating");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("ReviewId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Description = "Amazing architecture! Plan to spend a whole day here if you are really into art. There are so many halls to see. There is also a line to see the Mona Lisa and you have to be quick to take your picture with the painting.",
                            DestinationId = 1,
                            Rating = 5,
                            UserName = "user1"
                        },
                        new
                        {
                            ReviewId = 2,
                            Description = "I loved this place. If your are an art lover, this place is a paradise for you. One day is not enough to visit the entire museum. But still you can visit the main attractions including the famous Mona Lisa.",
                            DestinationId = 1,
                            Rating = 4,
                            UserName = "user2"
                        },
                        new
                        {
                            ReviewId = 3,
                            Description = "Wow! Sydney Opera House is absolutely FABULOUS! What an elegant, gorgeous, impressive display of truly artistic architecture.  The beauty of this site is enhanced with each different view. ",
                            DestinationId = 2,
                            Rating = 4,
                            UserName = "user2"
                        },
                        new
                        {
                            ReviewId = 4,
                            Description = "This was a great way to get to know the city of Portland! It was fascinating to learn about one of the first wealthy families to live there. The mansion is really cool and the hike through forest park is a fun way to get there! ",
                            DestinationId = 3,
                            Rating = 3,
                            UserName = "user1"
                        },
                        new
                        {
                            ReviewId = 5,
                            Description = "It is one of the best places on South Korea to see the old architecture of a palace. Even traditional events are demonstrate times to time. The most interesting thing in this place is that you can take photographs with soldiers with traditional costumes.",
                            DestinationId = 5,
                            Rating = 5,
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.HasOne("TravelApi.Models.Destination", "Destination")
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
